/*
Copyright (c) 2009, Yahoo! Inc. All rights reserved.
Code licensed under the BSD License:
http://developer.yahoo.net/yui/license.txt
version: 2.8.0r4
*/
(function(){var Y=YAHOO.util;var Anim=function(el,attributes,duration,method){if(!el){}
this.init(el,attributes,duration,method);};Anim.NAME='Anim';Anim.prototype={toString:function(){var el=this.getEl()||{};var id=el.id||el.tagName;return(this.constructor.NAME+': '+id);},patterns:{noNegatives:/width|height|opacity|padding/i,offsetAttribute:/^((width|height)|(top|left))$/,defaultUnit:/width|height|top$|bottom$|left$|right$/i,offsetUnit:/\d+(em|%|en|ex|pt|in|cm|mm|pc)$/i},doMethod:function(attr,start,end){return this.method(this.currentFrame,start,end-start,this.totalFrames);},setAttribute:function(attr,val,unit){var el=this.getEl();if(this.patterns.noNegatives.test(attr)){val=(val>0)?val:0;}
if(attr in el&&!('style'in el&&attr in el.style)){el[attr]=val;}else{Y.Dom.setStyle(el,attr,val+unit);}},getAttribute:function(attr){var el=this.getEl();var val=Y.Dom.getStyle(el,attr);if(val!=='auto'&&!this.patterns.offsetUnit.test(val)){return parseFloat(val);}
var a=this.patterns.offsetAttribute.exec(attr)||[];var pos=!!(a[3]);var box=!!(a[2]);if('style'in el){if(box||(Y.Dom.getStyle(el,'position')=='absolute'&&pos)){val=el['offset'+a[0].charAt(0).toUpperCase()+a[0].substr(1)];}else{val=0;}}else if(attr in el){val=el[attr];}
return val;},getDefaultUnit:function(attr){if(this.patterns.defaultUnit.test(attr)){return'px';}
return'';},setRuntimeAttribute:function(attr){var start;var end;var attributes=this.attributes;this.runtimeAttributes[attr]={};var isset=function(prop){return(typeof prop!=='undefined');};if(!isset(attributes[attr]['to'])&&!isset(attributes[attr]['by'])){return false;}
start=(isset(attributes[attr]['from']))?attributes[attr]['from']:this.getAttribute(attr);if(isset(attributes[attr]['to'])){end=attributes[attr]['to'];}else if(isset(attributes[attr]['by'])){if(start.constructor==Array){end=[];for(var i=0,len=start.length;i<len;++i){end[i]=start[i]+attributes[attr]['by'][i]*1;}}else{end=start+attributes[attr]['by']*1;}}
this.runtimeAttributes[attr].start=start;this.runtimeAttributes[attr].end=end;this.runtimeAttributes[attr].unit=(isset(attributes[attr].unit))?attributes[attr]['unit']:this.getDefaultUnit(attr);return true;},init:function(el,attributes,duration,method){var isAnimated=false;var startTime=null;var actualFrames=0;el=Y.Dom.get(el);this.attributes=attributes||{};this.duration=!YAHOO.lang.isUndefined(duration)?duration:1;this.method=method||Y.Easing.easeNone;this.useSeconds=true;this.currentFrame=0;this.totalFrames=Y.AnimMgr.fps;this.setEl=function(element){el=Y.Dom.get(element);};this.getEl=function(){return el;};this.isAnimated=function(){return isAnimated;};this.getStartTime=function(){return startTime;};this.runtimeAttributes={};this.animate=function(){if(this.isAnimated()){return false;}
this.currentFrame=0;this.totalFrames=(this.useSeconds)?Math.ceil(Y.AnimMgr.fps*this.duration):this.duration;if(this.duration===0&&this.useSeconds){this.totalFrames=1;}
Y.AnimMgr.registerElement(this);return true;};this.stop=function(finish){if(!this.isAnimated()){return false;}
if(finish){this.currentFrame=this.totalFrames;this._onTween.fire();}
Y.AnimMgr.stop(this);};var onStart=function(){this.onStart.fire();this.runtimeAttributes={};for(var attr in this.attributes){this.setRuntimeAttribute(attr);}
isAnimated=true;actualFrames=0;startTime=new Date();};var onTween=function(){var data={duration:new Date()-this.getStartTime(),currentFrame:this.currentFrame};data.toString=function(){return('duration: '+data.duration+', currentFrame: '+data.currentFrame);};this.onTween.fire(data);var runtimeAttributes=this.runtimeAttributes;for(var attr in runtimeAttributes){this.setAttribute(attr,this.doMethod(attr,runtimeAttributes[attr].start,runtimeAttributes[attr].end),runtimeAttributes[attr].unit);}
actualFrames+=1;};var onComplete=function(){var actual_duration=(new Date()-startTime)/1000;var data={duration:actual_duration,frames:actualFrames,fps:actualFrames/actual_duration};data.toString=function(){return('duration: '+data.duration+', frames: '+data.frames+', fps: '+data.fps);};isAnimated=false;actualFrames=0;this.onComplete.fire(data);};this._onStart=new Y.CustomEvent('_start',this,true);this.onStart=new Y.CustomEvent('start',this);this.onTween=new Y.CustomEvent('tween',this);this._onTween=new Y.CustomEvent('_tween',this,true);this.onComplete=new Y.CustomEvent('complete',this);this._onComplete=new Y.CustomEvent('_complete',this,true);this._onStart.subscribe(onStart);this._onTween.subscribe(onTween);this._onComplete.subscribe(onComplete);}};Y.Anim=Anim;})();YAHOO.util.AnimMgr=new function(){var thread=null;var queue=[];var tweenCount=0;this.fps=1000;this.delay=1;this.registerElement=function(tween){queue[queue.length]=tween;tweenCount+=1;tween._onStart.fire();this.start();};this.unRegister=function(tween,index){index=index||getIndex(tween);if(!tween.isAnimated()||index===-1){return false;}
tween._onComplete.fire();queue.splice(index,1);tweenCount-=1;if(tweenCount<=0){this.stop();}
return true;};this.start=function(){if(thread===null){thread=setInterval(this.run,this.delay);}};this.stop=function(tween){if(!tween){clearInterval(thread);for(var i=0,len=queue.length;i<len;++i){this.unRegister(queue[0],0);}
queue=[];thread=null;tweenCount=0;}
else{this.unRegister(tween);}};this.run=function(){for(var i=0,len=queue.length;i<len;++i){var tween=queue[i];if(!tween||!tween.isAnimated()){continue;}
if(tween.currentFrame<tween.totalFrames||tween.totalFrames===null)
{tween.currentFrame+=1;if(tween.useSeconds){correctFrame(tween);}
tween._onTween.fire();}
else{YAHOO.util.AnimMgr.stop(tween,i);}}};var getIndex=function(anim){for(var i=0,len=queue.length;i<len;++i){if(queue[i]===anim){return i;}}
return-1;};var correctFrame=function(tween){var frames=tween.totalFrames;var frame=tween.currentFrame;var expected=(tween.currentFrame*tween.duration*1000/tween.totalFrames);var elapsed=(new Date()-tween.getStartTime());var tweak=0;if(elapsed<tween.duration*1000){tweak=Math.round((elapsed/expected-1)*tween.currentFrame);}else{tweak=frames-(frame+1);}
if(tweak>0&&isFinite(tweak)){if(tween.currentFrame+tweak>=frames){tweak=frames-(frame+1);}
tween.currentFrame+=tweak;}};this._queue=queue;this._getIndex=getIndex;};YAHOO.util.Bezier=new function(){this.getPosition=function(points,t){var n=points.length;var tmp=[];for(var i=0;i<n;++i){tmp[i]=[points[i][0],points[i][1]];}
for(var j=1;j<n;++j){for(i=0;i<n-j;++i){tmp[i][0]=(1-t)*tmp[i][0]+t*tmp[parseInt(i+1,10)][0];tmp[i][1]=(1-t)*tmp[i][1]+t*tmp[parseInt(i+1,10)][1];}}
return[tmp[0][0],tmp[0][1]];};};(function(){var ColorAnim=function(el,attributes,duration,method){ColorAnim.superclass.constructor.call(this,el,attributes,duration,method);};ColorAnim.NAME='ColorAnim';ColorAnim.DEFAULT_BGCOLOR='#fff';var Y=YAHOO.util;YAHOO.extend(ColorAnim,Y.Anim);var superclass=ColorAnim.superclass;var proto=ColorAnim.prototype;proto.patterns.color=/color$/i;proto.patterns.rgb=/^rgb\(([0-9]+)\s*,\s*([0-9]+)\s*,\s*([0-9]+)\)$/i;proto.patterns.hex=/^#?([0-9A-F]{2})([0-9A-F]{2})([0-9A-F]{2})$/i;proto.patterns.hex3=/^#?([0-9A-F]{1})([0-9A-F]{1})([0-9A-F]{1})$/i;proto.patterns.transparent=/^transparent|rgba\(0, 0, 0, 0\)$/;proto.parseColor=function(s){if(s.length==3){return s;}
var c=this.patterns.hex.exec(s);if(c&&c.length==4){return[parseInt(c[1],16),parseInt(c[2],16),parseInt(c[3],16)];}
c=this.patterns.rgb.exec(s);if(c&&c.length==4){return[parseInt(c[1],10),parseInt(c[2],10),parseInt(c[3],10)];}
c=this.patterns.hex3.exec(s);if(c&&c.length==4){return[parseInt(c[1]+c[1],16),parseInt(c[2]+c[2],16),parseInt(c[3]+c[3],16)];}
return null;};proto.getAttribute=function(attr){var el=this.getEl();if(this.patterns.color.test(attr)){var val=YAHOO.util.Dom.getStyle(el,attr);var that=this;if(this.patterns.transparent.test(val)){var parent=YAHOO.util.Dom.getAncestorBy(el,function(node){return!that.patterns.transparent.test(val);});if(parent){val=Y.Dom.getStyle(parent,attr);}else{val=ColorAnim.DEFAULT_BGCOLOR;}}}else{val=superclass.getAttribute.call(this,attr);}
return val;};proto.doMethod=function(attr,start,end){var val;if(this.patterns.color.test(attr)){val=[];for(var i=0,len=start.length;i<len;++i){val[i]=superclass.doMethod.call(this,attr,start[i],end[i]);}
val='rgb('+Math.floor(val[0])+','+Math.floor(val[1])+','+Math.floor(val[2])+')';}
else{val=superclass.doMethod.call(this,attr,start,end);}
return val;};proto.setRuntimeAttribute=function(attr){superclass.setRuntimeAttribute.call(this,attr);if(this.patterns.color.test(attr)){var attributes=this.attributes;var start=this.parseColor(this.runtimeAttributes[attr].start);var end=this.parseColor(this.runtimeAttributes[attr].end);if(typeof attributes[attr]['to']==='undefined'&&typeof attributes[attr]['by']!=='undefined'){end=this.parseColor(attributes[attr].by);for(var i=0,len=start.length;i<len;++i){end[i]=start[i]+end[i];}}
this.runtimeAttributes[attr].start=start;this.runtimeAttributes[attr].end=end;}};Y.ColorAnim=ColorAnim;})();YAHOO.util.Easing={easeNone:function(t,b,c,d){return c*t/d+b;},easeIn:function(t,b,c,d){return c*(t/=d)*t+b;},easeOut:function(t,b,c,d){return-c*(t/=d)*(t-2)+b;},easeBoth:function(t,b,c,d){if((t/=d/2)<1){return c/2*t*t+b;}
return-c/2*((--t)*(t-2)-1)+b;},easeInStrong:function(t,b,c,d){return c*(t/=d)*t*t*t+b;},easeOutStrong:function(t,b,c,d){return-c*((t=t/d-1)*t*t*t-1)+b;},easeBothStrong:function(t,b,c,d){if((t/=d/2)<1){return c/2*t*t*t*t+b;}
return-c/2*((t-=2)*t*t*t-2)+b;},elasticIn:function(t,b,c,d,a,p){if(t==0){return b;}
if((t/=d)==1){return b+c;}
if(!p){p=d*.3;}
if(!a||a<Math.abs(c)){a=c;var s=p/4;}
else{var s=p/(2*Math.PI)*Math.asin(c/a);}
return-(a*Math.pow(2,10*(t-=1))*Math.sin((t*d-s)*(2*Math.PI)/p))+b;},elasticOut:function(t,b,c,d,a,p){if(t==0){return b;}
if((t/=d)==1){return b+c;}
if(!p){p=d*.3;}
if(!a||a<Math.abs(c)){a=c;var s=p/4;}
else{var s=p/(2*Math.PI)*Math.asin(c/a);}
return a*Math.pow(2,-10*t)*Math.sin((t*d-s)*(2*Math.PI)/p)+c+b;},elasticBoth:function(t,b,c,d,a,p){if(t==0){return b;}
if((t/=d/2)==2){return b+c;}
if(!p){p=d*(.3*1.5);}
if(!a||a<Math.abs(c)){a=c;var s=p/4;}
else{var s=p/(2*Math.PI)*Math.asin(c/a);}
if(t<1){return-.5*(a*Math.pow(2,10*(t-=1))*Math.sin((t*d-s)*(2*Math.PI)/p))+b;}
return a*Math.pow(2,-10*(t-=1))*Math.sin((t*d-s)*(2*Math.PI)/p)*.5+c+b;},backIn:function(t,b,c,d,s){if(typeof s=='undefined'){s=1.70158;}
return c*(t/=d)*t*((s+1)*t-s)+b;},backOut:function(t,b,c,d,s){if(typeof s=='undefined'){s=1.70158;}
return c*((t=t/d-1)*t*((s+1)*t+s)+1)+b;},backBoth:function(t,b,c,d,s){if(typeof s=='undefined'){s=1.70158;}
if((t/=d/2)<1){return c/2*(t*t*(((s*=(1.525))+1)*t-s))+b;}
return c/2*((t-=2)*t*(((s*=(1.525))+1)*t+s)+2)+b;},bounceIn:function(t,b,c,d){return c-YAHOO.util.Easing.bounceOut(d-t,0,c,d)+b;},bounceOut:function(t,b,c,d){if((t/=d)<(1/2.75)){return c*(7.5625*t*t)+b;}else if(t<(2/2.75)){return c*(7.5625*(t-=(1.5/2.75))*t+.75)+b;}else if(t<(2.5/2.75)){return c*(7.5625*(t-=(2.25/2.75))*t+.9375)+b;}
return c*(7.5625*(t-=(2.625/2.75))*t+.984375)+b;},bounceBoth:function(t,b,c,d){if(t<d/2){return YAHOO.util.Easing.bounceIn(t*2,0,c,d)*.5+b;}
return YAHOO.util.Easing.bounceOut(t*2-d,0,c,d)*.5+c*.5+b;}};(function(){var Motion=function(el,attributes,duration,method){if(el){Motion.superclass.constructor.call(this,el,attributes,duration,method);}};Motion.NAME='Motion';var Y=YAHOO.util;YAHOO.extend(Motion,Y.ColorAnim);var superclass=Motion.superclass;var proto=Motion.prototype;proto.patterns.points=/^points$/i;proto.setAttribute=function(attr,val,unit){if(this.patterns.points.test(attr)){unit=unit||'px';superclass.setAttribute.call(this,'left',val[0],unit);superclass.setAttribute.call(this,'top',val[1],unit);}else{superclass.setAttribute.call(this,attr,val,unit);}};proto.getAttribute=function(attr){if(this.patterns.points.test(attr)){var val=[superclass.getAttribute.call(this,'left'),superclass.getAttribute.call(this,'top')];}else{val=superclass.getAttribute.call(this,attr);}
return val;};proto.doMethod=function(attr,start,end){var val=null;if(this.patterns.points.test(attr)){var t=this.method(this.currentFrame,0,100,this.totalFrames)/100;val=Y.Bezier.getPosition(this.runtimeAttributes[attr],t);}else{val=superclass.doMethod.call(this,attr,start,end);}
return val;};proto.setRuntimeAttribute=function(attr){if(this.patterns.points.test(attr)){var el=this.getEl();var attributes=this.attributes;var start;var control=attributes['points']['control']||[];var end;var i,len;if(control.length>0&&!(control[0]instanceof Array)){control=[control];}else{var tmp=[];for(i=0,len=control.length;i<len;++i){tmp[i]=control[i];}
control=tmp;}
if(Y.Dom.getStyle(el,'position')=='static'){Y.Dom.setStyle(el,'position','relative');}
if(isset(attributes['points']['from'])){Y.Dom.setXY(el,attributes['points']['from']);}
else{Y.Dom.setXY(el,Y.Dom.getXY(el));}
start=this.getAttribute('points');if(isset(attributes['points']['to'])){end=translateValues.call(this,attributes['points']['to'],start);var pageXY=Y.Dom.getXY(this.getEl());for(i=0,len=control.length;i<len;++i){control[i]=translateValues.call(this,control[i],start);}}else if(isset(attributes['points']['by'])){end=[start[0]+attributes['points']['by'][0],start[1]+attributes['points']['by'][1]];for(i=0,len=control.length;i<len;++i){control[i]=[start[0]+control[i][0],start[1]+control[i][1]];}}
this.runtimeAttributes[attr]=[start];if(control.length>0){this.runtimeAttributes[attr]=this.runtimeAttributes[attr].concat(control);}
this.runtimeAttributes[attr][this.runtimeAttributes[attr].length]=end;}
else{superclass.setRuntimeAttribute.call(this,attr);}};var translateValues=function(val,start){var pageXY=Y.Dom.getXY(this.getEl());val=[val[0]-pageXY[0]+start[0],val[1]-pageXY[1]+start[1]];return val;};var isset=function(prop){return(typeof prop!=='undefined');};Y.Motion=Motion;})();(function(){var Scroll=function(el,attributes,duration,method){if(el){Scroll.superclass.constructor.call(this,el,attributes,duration,method);}};Scroll.NAME='Scroll';var Y=YAHOO.util;YAHOO.extend(Scroll,Y.ColorAnim);var superclass=Scroll.superclass;var proto=Scroll.prototype;proto.doMethod=function(attr,start,end){var val=null;if(attr=='scroll'){val=[this.method(this.currentFrame,start[0],end[0]-start[0],this.totalFrames),this.method(this.currentFrame,start[1],end[1]-start[1],this.totalFrames)];}else{val=superclass.doMethod.call(this,attr,start,end);}
return val;};proto.getAttribute=function(attr){var val=null;var el=this.getEl();if(attr=='scroll'){val=[el.scrollLeft,el.scrollTop];}else{val=superclass.getAttribute.call(this,attr);}
return val;};proto.setAttribute=function(attr,val,unit){var el=this.getEl();if(attr=='scroll'){el.scrollLeft=val[0];el.scrollTop=val[1];}else{superclass.setAttribute.call(this,attr,val,unit);}};Y.Scroll=Scroll;})();YAHOO.register("animation",YAHOO.util.Anim,{version:"2.8.0r4",build:"2449"});
YAHOO.namespace('YAHOO.Finance.TradeNow');YAHOO.Finance.TradeNow=function(){var userLoggedIn=0;var userBrokerPref=null;var userBrokerUrl='';var userBrokerImg='';var userBrokerTxt='';var popupDialog;var btnClass;var spaceid;var errDiv=document.getElementById('trdnow_err');var yEvent=YAHOO.util.Event;var yDom=YAHOO.util.Dom;var oAC;var oDS;var yWA;var txtNoBrkr;var txtSelBrkr;var anim;var firsttime=0;var init=function(){spaceid=(YAHOO.util.Dom.get("spaceid")).innerHTML;if(!YAHOO.Finance.TradeNowConfig)
return;yWA=YAHOO.Finance.TradeNowConfig.ywa;txtNoBrkr=YAHOO.Finance.TradeNowConfig.txt_nobrkr;txtSelBrkr=YAHOO.Finance.TradeNowConfig.txt_selbrkr;if(yDom.get('trdnow_user_status')){userLoggedIn=(yDom.get('trdnow_user_status')).value;}
var btn=yDom.get('btn_trdnow');if(yDom.getAttribute(btn,'href'))
userBrokerUrl=yDom.getAttribute(btn,'href');if(yDom.getAttribute(btn,'bid')&&yDom.getAttribute(btn,'bid')!='')
userBrokerPref=yDom.getAttribute(btn,'bid');if(yDom.getAttribute(btn,'btxt'))
userBrokerTxt=yDom.getAttribute(btn,'btxt');if(YAHOO.Finance.Cookie.getObj('PRF')){var cookieval=null;var custflg=0;var fndflg=0;var Config=YAHOO.Finance.TradeNowConfig.config;var customConfig=YAHOO.Finance.TradeNowConfig.custom;financeCookie=YAHOO.Finance.Cookie.getObj('PRF');if(financeCookie.bid&&financeCookie.bid!=''&&(financeCookie.bid).toLowerCase()!='null'){cookieval=financeCookie.bid;}
if(cookieval&&cookieval!=userBrokerPref){for(var j=0;j<Config.length;j++){if(Config[j].id==cookieval){userBrokerPref=Config[j].id;userBrokerUrl=Config[j].broker_url;userBrokerTxt=Config[j].name;userBrokerImg=Config[j].button_url;fndflg=1;break;}}
for(var j=0;j<customConfig.length&&!fndflg;j++){if(customConfig[j].id==cookieval){userBrokerPref=customConfig[j].id;userBrokerUrl=customConfig[j].url;userBrokerTxt=customConfig[j].name;custflg=1;break;}}
var brokerurl=yDom.get("txt_custombrkr");if(custflg){brokerUrl=(brokerurl)?brokerurl.value:'';if(userBrokerTxt.toString()!=brokerUrl.toString()){brokerurl.value=userBrokerTxt;}
var customRadio=yDom.getElementsByClassName('custombrkr','input','yfi_tradenow');customRadio[0].checked=true;}else{brokerurl.value='';var brokerList=yDom.getElementsByClassName('r_selbrkr','input','yfi_tradenow');for(var i=0;i<brokerList.length;i++){if(brokerList[i].value==userBrokerPref){brokerList[i].checked=true;}}}
updateDomOnBrkrChg();}
else if(!cookieval&&userBrokerPref){userBrokerPref=null;userBrokerUrl='';userBrokerImg=null;userBrokerTxt='';updateDomonBrkrReset();}}
initAutoComplete();displayPlaceHolder('1');displayAutoComplete();anim=new YAHOO.util.Anim('trdnow_success',{opacity:{from:1,to:0}},5,YAHOO.util.Easing.EaseOut);anim.onStart.subscribe(function(){var succTxtField=yDom.get('trdnow_success');succTxtField.innerHTML="Broker Saved";yDom.setStyle(succTxtField,'display','inline');});anim.onComplete.subscribe(function(){var succTxtField=yDom.get('trdnow_success');succTxtField.innerHTML="";yDom.setStyle(succTxtField,'display','none');});};var displayPlaceHolder=function(flg){var tempInputElem=document.createElement('input');var isPlaceHolder=('placeholder'in tempInputElem);if(!isPlaceHolder){var acInputBox=yDom.get('txt_custombrkr');var placeholderValue=yDom.getAttribute(acInputBox,'placeholder');var preIntVal=acInputBox.value;if(flg=='1')
{yEvent.on(acInputBox,"focus",function(e){this.value='';yDom.removeClass(this,'hint');});yEvent.on(acInputBox,"blur",function(e){var value=this.value;if(value===null||value.length===0){this.value=placeholderValue;yDom.addClass(this,'hint');}});}
if(preIntVal===undefined||preIntVal.length===0||preIntVal===placeholderValue){acInputBox.value=placeholderValue;yDom.addClass(acInputBox,'hint');}}};var displayAutoComplete=function(){var acInputBox=yDom.get('txt_custombrkr');yEvent.on(acInputBox,"focus",function(e){var acInputBox=yDom.get('txt_custombrkr');var placeholderValue=yDom.getAttribute(acInputBox,'placeholder');var preIntVal=acInputBox.value;var customRadio=yDom.getElementsByClassName('custombrkr','input','yfi_tradenow');customRadio[0].checked=true;if(preIntVal===undefined||preIntVal.length===0||preIntVal===placeholderValue){oAC.sendQuery("");}else{oAC.expandContainer();}});};var saveSettingsCookie=function(){if(typeof YAHOO.Finance.Cookie.getObj=='function'&&typeof YAHOO.Finance.Cookie.set=='function'){if(YAHOO.Finance.Cookie.getObj('PRF')){if(YAHOO.Finance.Cookie.jar.PRF){YAHOO.Finance.Cookie.jar.PRF=null;}
var cookieObj=YAHOO.Finance.Cookie.getObj('PRF');cookieObj.bid=userBrokerPref;YAHOO.Finance.Cookie.set('PRF',cookieObj,3650);}}};var updateDomOnBrkrChg=function(){var btn=yDom.get('btn_trdnow');btn.removeAttribute('disabled');yDom.setAttribute(btn,'bid',userBrokerPref);yDom.setAttribute(btn,'href',userBrokerUrl);yDom.setAttribute(btn,'btxt',userBrokerTxt);if(userBrokerImg!=''&&userBrokerImg!=null){btn.style.background="url('"+userBrokerImg+"') no-repeat transparent";}else{btn.style.background='';btn.removeAttribute('style');}
var txt=yDom.getElementsByClassName('brokertxt','div','btn_selbrkr');if(YAHOO.env.ua.ie==6||YAHOO.env.ua.ie==7)
{txt[0].innerHTML="<b>"+userBrokerTxt+" </b>|"+txtSelBrkr;}else{txt[0].innerHTML="<b>"+userBrokerTxt+"</b>&nbsp;|&nbsp;"+txtSelBrkr;}};var updateButtonAttr=function(){var YWATracker=YWA.getTracker(yWA);YWATracker.setAction('12');YWATracker.setCF(21,'tradenow');YWATracker.setCF(17,'tradenowsave');YWATracker.setCF(18,userLoggedIn);YWATracker.setCF(22,userBrokerPref);YWATracker.submit_action();updateDomOnBrkrChg();anim.animate();anim.animate();changeSelWindowState();};var saveSettingsUDB=function(callopt){var crumbEl=YAHOO.util.Dom.get(".yficrumb");var crumbValue=(crumbEl!=null)?crumbEl.value:"";var sUrl="/webservice/v1/preferences?.yficrumb="+crumbValue;var postData="broker_id="+callopt.bid;var settingsUDBCallback={failure:function(o){errDiv.innerHTML="Unable to save settings.Please try later.";yDom.setStyle(errDiv,'display','inline');},timeout:5000,argument:[callopt.bid,callopt.url,callopt.img,callopt.txt]};if(callopt.action=="save"){settingsUDBCallback.success=function(o){if(o.status==200){userBrokerPref=o.argument[0];userBrokerUrl=o.argument[1];userBrokerImg=o.argument[2];userBrokerTxt=o.argument[3];saveSettingsCookie();updateButtonAttr();}};}else{settingsUDBCallback.success=function(o){if(o.status==200){userBrokerPref=null;userBrokerUrl='';userBrokerImg=null;userBrokerTxt='';resetBtnAttr();}};}
YAHOO.util.Connect.initHeader("Content-Type","application/x-www-form-urlencoded");var request=YAHOO.util.Connect.asyncRequest('POST',sUrl,settingsUDBCallback,postData);};var saveBrokerPref=function(){var brokerList=yDom.getElementsByClassName('r_selbrkr','input','yfi_tradenow');var selBroker="";var selBrokerUrl="";var selBrokerTxt="";var selBrokerImg="";var brokerUrl="";var customflg=0;var flg=0;for(var i=0;i<brokerList.length;i++){if(brokerList[i].checked){selBroker=brokerList[i].value;if(yDom.hasClass(brokerList[i],'custombrkr')){var Config=YAHOO.Finance.TradeNowConfig.custom;for(var j=0;j<Config.length;j++){if(Config[j].id==selBroker){selBrokerUrl=Config[j].url;selBrokerTxt=Config[j].name;customflg=1;break;}}
brokerurl=yDom.get("txt_custombrkr");brokerUrl=(brokerurl)?brokerurl.value:'';if((selBrokerTxt.toString()!=brokerUrl.toString()||selBrokerUrl=='')){flg=-1;break;}}
else{var Config=YAHOO.Finance.TradeNowConfig.config;for(var j=0;j<Config.length;j++){if(Config[j].id==selBroker){selBrokerUrl=Config[j].broker_url;selBrokerTxt=Config[j].name;selBrokerImg=Config[j].button_url;break;}}}
flg=1;}}
if(!flg){errDiv.innerHTML="Please select a broker above";yDom.setStyle(errDiv,'display','inline');}else if(flg==-1){errDiv.innerHTML="Please select a valid broker";yDom.setStyle(errDiv,'display','inline');}else{if(customflg==0){var custombrkr=yDom.get("txt_custombrkr");custombrkr.value="";displayPlaceHolder('0');}
if(userLoggedIn==1){saveSettingsUDB({'bid':selBroker,'url':selBrokerUrl,'img':selBrokerImg,'txt':selBrokerTxt,'action':'save'});}else{userBrokerPref=selBroker;userBrokerTxt=selBrokerTxt;userBrokerImg=selBrokerImg;userBrokerUrl=selBrokerUrl;saveSettingsCookie();updateButtonAttr();}}};var redirectBrokerSite=function(e){var btn=e.Target;var divid=yDom.get('yfi_tradenow');var YWATracker=YWA.getTracker(yWA);YWATracker.setAction('05');YWATracker.setCF(21,'tradenow');YWATracker.setCF(17,'tradenowbrokerclick');YWATracker.setCF(18,userLoggedIn);YWATracker.setCF(22,userBrokerPref);YWATracker.submit_action();if(!popupDialog)
{popupDialog=new YAHOO.widget.Panel("lve_trdnow",{width:"300px",height:"90px",fixedcenter:true,close:false,draggable:false,underlay:"matte",zindex:2,modal:true,visible:true});popupDialog.setHeader("Redirecting to external site, please wait...");popupDialog.setBody("<img src=\"http://l.yimg.com/a/i/us/per/gr/gp/rel_interstitial_loading.gif\"/>");popupDialog.render(divid);popupDialog.cfg.setProperty("context",[btn,"tl","br"]);}
popupDialog.show();var t=setTimeout(function(){popupDialog.hide();window.location=userBrokerUrl;},2000);};var changeSelWindowState=function(){var btnSel=yDom.get('btn_arrow');var div=yDom.get('trdnow_sel');var btnClass=yDom.getAttribute(btnSel,'class');errDiv.innerHTML="";yDom.setStyle(errDiv,'display','none');if(btnClass.indexOf('upmenu')>=0)
{yDom.setStyle(div,'display','none');yDom.setAttribute(btnSel,'class','downmenu');}
else
{yDom.setStyle(div,'display','block');yDom.setAttribute(btnSel,'class','upmenu');}};var resetUserPref=function(e){yEvent.preventDefault(e);if(userLoggedIn==1){saveSettingsUDB({'bid':null,'url':'','img':null,'txt':'','action':'reset'});}
else{userBrokerPref=null;userBrokerUrl='';userBrokerImg=null;userBrokerTxt='';resetBtnAttr();}};var updateDomonBrkrReset=function(){if(!userBrokerPref){var btn=yDom.get('btn_trdnow');yDom.setAttribute(btn,'disabled','disabled');yDom.setAttribute(btn,'bid','');yDom.setAttribute(btn,'href','');btn.style.background="";btn.removeAttribute('style');var brokerList=yDom.getElementsByClassName('r_selbrkr','input','yfi_tradenow');for(var i=0;i<brokerList.length;i++){brokerList[i].checked=false;}
var custxt=yDom.get('txt_custombrkr');custxt.value="";displayPlaceHolder('0');var txt=yDom.getElementsByClassName('brokertxt','div','btn_selbrkr');txt[0].innerHTML=txtNoBrkr;}};var resetBtnAttr=function(){if(!userBrokerPref)
{saveSettingsCookie();updateDomonBrkrReset();}};var initAutoComplete=function(){if(!oAC){oDS=new YAHOO.util.LocalDataSource(YAHOO.Finance.TradeNowConfig);oDS.responseSchema={resultsList:"custom",fields:["name","id","url"]};oAC=new YAHOO.widget.AutoComplete("txt_custombrkr","trdnow_container",oDS);oAC.animVert=false;oAC.allowBrowserAutocomplete=false;oAC.typeAhead=true;oAC.forceSelection=false;oAC.alwaysShowContainer=false;oAC.minQueryLength=0;oAC.maxResultsDsiaplyed=50;oAC.autoHighlight=false;var eleContent=oAC._elContent;yDom.setStyle(eleContent,"overflowY","auto");oAC.itemSelectEvent.subscribe(function(s,aArgs){var txtval1=yDom.getElementsByClassName("custombrkr",'input','yfi_tradenow');var txtval=txtval1[0];var oData=aArgs[2];txtval.checked=true;yDom.setAttribute(txtval,'value',oData[1]);});oAC.itemArrowToEvent.subscribe(function(s,aArgs){var listItem=aArgs[1]
var data=oAC.getListItemData(listItem);var txtval1=yDom.getElementsByClassName("custombrkr",'input','yfi_tradenow');var txtval=txtval1[0];txtval.checked=true;yDom.setAttribute(txtval,'value',data[1]);var txtField=yDom.get("txt_custombrkr");txtField.value=data[0];});oAC.formatResult=function(oResultData,sQuery,sResultMatch){return(oResultData[0]);};}};init();return{tradeNow:redirectBrokerSite,saveBroker:saveBrokerPref,changeState:changeSelWindowState,resetBroker:resetUserPref};};tradenow_obj=new YAHOO.Finance.TradeNow();YAHOO.util.Event.addListener('btn_trdnow','click',tradenow_obj.tradeNow,tradenow_obj);YAHOO.util.Event.addListener('btn_savebrkr','click',tradenow_obj.saveBroker,tradenow_obj);YAHOO.util.Event.addListener('btn_selbrkr','click',tradenow_obj.changeState,tradenow_obj);YAHOO.util.Event.addListener('reset_brkr','click',tradenow_obj.resetBroker,tradenow_obj);